# _stubs/busio.pyi

"""
Stub rozhraní pro CircuitPython modul `busio`.

Obsahuje třídy I2C, SPI a UART s jejich veřejným API.
"""

class I2C:
    def __init__(self, scl, sda, frequency: int = 400000): ...
    def try_lock(self) -> bool: ...
    def unlock(self) -> None: ...
    def scan(self) -> list[int]: ...
    def readfrom_into(self, address: int, buffer, *, start: int = 0, end: int | None = None) -> None: ...
    def writeto(self, address: int, buffer, *, start: int = 0, end: int | None = None, stop: bool = True) -> None: ...
    def writeto_then_readfrom(
        self,
        address: int,
        out_buffer,
        in_buffer,
        *,
        out_start: int = 0,
        out_end: int | None = None,
        in_start: int = 0,
        in_end: int | None = None,
    ) -> None: ...


class SPI:
    def __init__(self, clock=None, MOSI=None, MISO=None): ...
    def try_lock(self) -> bool: ...
    def unlock(self) -> None: ...
    def configure(self, *, baudrate: int = 1000000, polarity: int = 0, phase: int = 0, bits: int = 8) -> None: ...
    def write(self, data) -> None: ...
    def readinto(self, buffer) -> None: ...
    def write_readinto(self, out_buffer, in_buffer) -> None: ...


class UART:
    def __init__(self, tx=None, rx=None, baudrate: int = 9600, bits: int = 8, parity=None, stop: int = 1): ...
    def read(self, nbytes: int | None = None): ...
    def readinto(self, buffer) -> int | None: ...
    def write(self, data) -> int: ...
    def any(self) -> int: ...
